[package]
name        = "startt"
version     = "0.1.0"
edition     = "2024"
authors     = ["David Horner"]
description = "Automate detection of HWND and real PID for apps launched through ShellExecuteEx (cmd start, Explorer, PowerShell)"
license     = "MIT"
repository  = "https://github.com/davehorner/startt"
homepage    = "https://github.com/davehorner/startt"
documentation = "https://docs.rs/startt"
readme      = "README.md"
keywords    = ["windows", "cli", "automation", "hwnd", "shell", "shellexecute"]
categories  = ["command-line-utilities", "windows"] 

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
widestring = "1.2.0"
winapi = { version = "0.3.9", features = ["handleapi", "libloaderapi", "psapi", "shellapi", "tlhelp32", "winbase", "winuser"] }
# windows = { version = "0.61.1", features = ["Win32_Foundation", "Win32_UI_Shell", "Win32_System_Threading","Win32_UI_WindowsAndMessaging","Win32_System_Registry"] }
